# Justin Choi (jc8mc) 
# CS 2150 - 106 
# April 14th 2017 

CC = clang 
CFLAGS = -Wall -O2 
OFILES = linkedlist.c 
.SUFFIXES: .o .c 
main: $(OFILES) 
	$(CC) $(OFILES) $(CFLAGS)
clean:
	/bin/rm -f *.o *~
